- id: check-aws-profile
  name: Terraform AWS Profiles
  description: Detect AWS profiles in Terraform scripts and compare with YAML file
  entry: check-aws-profile
  language: python
  language_version: python3
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
